### ISSUE TITLE
[Bug Report] Error when trying to run on iOS simulator

### ISSUE THREAD

**Issue by armanhadifatah** [alexmercerind/media_kit#103]
Hello dear 

I get this error when I want to run it  from xcode for simulator 

`Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/arman/.pub-cache/hosted/pub.dev/media_kit_libs_ios_video-1.0.0/ios/Libs/libmpv.dylib' for architecture arm64`

and i use these in my pubspec.yaml

```
  media_kit: ^0.0.2
  media_kit_libs_ios_video: ^1.0.0
```

**Comment by alexmercerind** [comment]
Hi @armanhadifatah,

Please update the dependencies, we just released a fix:

```yaml
dependencies:
  media_kit: ^0.0.3
  # For video rendering.
  media_kit_video: ^0.0.2
  # Enables support for higher number of concurrent instances. Optional.
  media_kit_native_event_loop: ^1.0.1
  # Pick based on your requirements / platform:
  media_kit_libs_windows_video: ^1.0.1          # Windows package for video (& audio) native libraries.
  media_kit_libs_ios_video: ^1.0.1              # iOS package for video (& audio) native libraries.
  media_kit_libs_macos_video: ^1.0.1            # macOS package for video (& audio) native libraries.
  media_kit_libs_linux: ^1.0.1                  # Linux dependency package.
```

I hope this will work.

**Comment by alexmercerind** [comment]
Works?

**Comment by armanhadifatah** [comment]
Now it give me this error

`Library not found for -lmpv`

**Comment by alexmercerind** [comment]
flutter clean?

Our CI is working for iOS: https://github.com/alexmercerind/media_kit/actions/runs/4601024537/jobs/8128542838

**Comment by zezo357** [comment]
> flutter clean?
> 
> Our CI is working for iOS: https://github.com/alexmercerind/media_kit/actions/runs/4601024537/jobs/8128542838

i think https://github.com/alexmercerind/media_kit/pull/97 updated both media_kit_video and media_kit_native_event_loop
too.

this is why it fails in our side

**Comment by alexmercerind** [comment]
Good call!

**Comment by armanhadifatah** [comment]
I updated everything also run flutter clean pod update on ios folder but i get this error 

<img width="1440" alt="Screen Shot 2023-04-04 at 12 01 20 AM" src="https://user-images.githubusercontent.com/48276427/229626863-78655133-c11a-40b2-a827-51c254260b1c.png">


```
media_kit_native_event_loop
       Library not found for -lmpv
```

**Comment by alexmercerind** [comment]
flutter pub get now

**Comment by zezo357** [comment]
https://pub.dev/packages/media_kit_video

> flutter pub get now

is still 0.0.2, not updated (just letting you know)

**Comment by alexmercerind** [comment]
Use media_kit_video: ^0.0.3

**Comment by zezo357** [comment]
> Guys I did everything this is what i have in my pubspec.yaml
> 
> ```
>   flutter_meedu_videoplayer: 4.0.8
>   media_kit: ^0.0.3+1
>   media_kit_video: ^0.0.2
>   media_kit_libs_ios_video: ^1.0.1
>   media_kit_native_event_loop: ^1.0.2
> ```
> 
> I still get the error
> 
> ```
> media_kit_native_event_loop
>        Library not found for -lmpv
> ```
flutter_meedu_videoplayer i didnt update it yet, it will miss up the build for you until i update it

**Comment by birros** [comment]
@armanhadifatah The following versions will solve your problem.
This is due to an error on my part (see #105)
Sorry...

```yaml
media_kit_video: ^0.0.4
media_kit_libs_ios_video: ^1.0.2
media_kit_libs_macos_video: ^1.0.2
```
