### ISSUE TITLE
[Enhancement] seamless loop

### ISSUE THREAD

**Issue by zhahouming** [alexmercerind/media_kit#150]
In the single file loop playback mode, there is a delay between the two loops, which prevents a perfect seamless connection. This is a problem with the original MPV library, and here is the related fix PR link https://github.com/mpv-player/mpv/pull/10748, FYI.

**Comment by rekire** [comment]
Is there currently a workaround for looping videos?

**Comment by alexmercerind** [comment]
@rekire

> Is there currently a workaround for looping videos?

There's a dedicated solution, not a workaround.

```dart
await player.setPlaylistMode(PlaylistMode.loop);
```

This issue is for seamless loop, not loop.

**Comment by nialljawad96** [comment]
Second this. Looping with a gap breaks the experience.

**Comment by zhahouming** [comment]
> Second this. Looping with a gap breaks the experience.

@nialljawad96 The MKV repository needs to merge this pull request first. People with requirements can go there and leave more comments. https://github.com/mpv-player/mpv/pull/10748,

**Comment by moffatman** [comment]
Note for future fix

This is due to `mpv_get_property` within render callback to find the current video width/height, which is not allowed per mpv docs. Need to subscribe to those properties in another thread and send them to be cached in render thread

**Comment by elvinasn** [comment]
Any news on this? The gap really breaks the good experience.

**Comment by Helium-Hydride** [comment]
Is there any progress on this?

**Comment by inc16sec** [comment]
Any update?

**Comment by abdelaziz-mahdy** [comment]
it may be fixed by the new changes so you try using the github main branch 

```
dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```
