### ISSUE TITLE
[Bug Report][Android] x86_64 crash

### ISSUE THREAD

**Issue by coolight7** [alexmercerind/media_kit#210]
Hello,
* Crash when start App on the Mi PAD 2.
* There are some errors on console:
```
F/flutter (12326): [FATAL:flutter/fml/platform/android/message_loop_android.cc(54)] Check failed: add_result == 1. 
F/flutter (12383): [FATAL:flutter/fml/platform/android/message_loop_android.cc(54)] Check failed: add_result == 1. 
F/flutter (12443): [FATAL:flutter/fml/platform/android/message_loop_android.cc(54)] Check failed: add_result == 1.
```
* There are some information about Mi PAD 2:
```
Android 5.1
CPU: Intel Atom x5-Z8500 ( x86_64 )
RAM: 2G
```
* I had try:
  * Flutter 3.7 (crach)
  * Flutter 3.10 (crash)
  * remove media_kit package and run on Mi PAD 2 ( ok )
  * use media_kit and run (Debug) on Virtual x86 Android 6.0 (crash, if run Release will get an error: Exception: Release mode is not supported for Android SDK built for x86.)
  * remove media_kit package and run (Debug) on Virtual x86 Android 6.0 (ok)
  * use media_kit and run on Android 11 arm64 ( ok )
  * use media_kit and run on Android 4.4 arm ( ok, no crash when start app )
* Sorry, my English is so poor.
* Thanks to anybody who replies.

**Comment by alexmercerind** [comment]
Flutter doesn't even support x86 you genius.

**Comment by coolight7** [comment]
> Flutter doesn't even support x86 you genius.

But I can run release on Mi PAD 2 if remove media_kit package.
I know the release mode not support for x86. 
But it can run debug on Virtual x86 Android if remove media_kit package, I think it maybe have some similarities and help for solve this issue.

**Comment by alexmercerind** [comment]
Which APK are you running x86_64 or arm64 or armeabi?

**Comment by coolight7** [comment]
> Which APK are you running x86_64 or arm64 or armeabi?

I find the libflutter.so only in release APK/lib/x86_64.
I find the information about inter Atom x5-Z8500 is x86.
I don't know the inter Atom x5-Z8500 how to run as x86_64 .....

**Comment by coolight7** [comment]
> [Flutter doesn't support x86 on any platform; including Android](https://github.com/flutter/flutter/issues/9253). However, Flutter does run on x86 in Debug (because Dart has support for x86 JIT) _i.e._ generally emulators that run on AMD based CPUs. We support them; like Flutter does.
> 
> In release builds however, you can't target x86 market with Flutter. It's very nominal regardless.

oh sorry, Bing tell me intel Atom x5-Z8500 is support 64bit, so it is x64.

**Comment by coolight7** [comment]
> I can't confirm for your device, it should be x86_64 then. Where, x86_64 APK should work fine.

yea, Looking forward to resolving this issue.

**Comment by lucinhu** [comment]
This crash can also appear in Android 5 to 6 emulators (both arm64 and x86_64).

**Comment by alexmercerind** [comment]
Hey guys! I've found the cause & I'm on it. Give me some time.

**Comment by mcLYX** [comment]
It also crashed when I running an app (bili_you) which use media_kit on a Android 5.0.2 arm(MT6580) device.
I'm not sure why, because this device has only 512MB RAM.
But a user of bili_you run it on a mi phone (SnapDragon 625, Android 6.0, MIUI10, 2GB RAM) crashed too, so I don't think it's a OOM problem.

Sorry, my English is poor. I'm not sure if my expression is clear

**Comment by alexmercerind** [comment]
Hey guys,

@coolight7 @mcLYX @lucinhu 

May y'all confirm the fix:

https://github.com/alexmercerind/media_kit/actions/runs/5104934568

Do these APK crash?

**Comment by 1598266725** [comment]
> Hey guys,
> 
> @coolight7 @mcLYX @lucinhu 
> 
> May y'all confirm the fix:
> 
> https://github.com/alexmercerind/media_kit/actions/runs/5104934568
> 
> Do these APK crash?

Hello, have you fixed this issue?

**Comment by 1598266725** [comment]
> Hey guys,
> 
> @coolight7 @mcLYX @lucinhu 
> 
> May y'all confirm the fix:
> 
> https://github.com/alexmercerind/media_kit/actions/runs/5104934568
> 
> Do these APK crash?

Hello, my phone system is Android 6.0. After reading your reply, I tried Biliyou and it still shows that the software has stopped running. I'm not sure if you have fixed it or if the author wants to update it

**Comment by alexmercerind** [comment]
Does my APK crash?

https://github.com/alexmercerind/media_kit/actions/runs/5104934568

Scroll down for links.

I will publish an update; and then BiliYou will be updated afterwards.

**Comment by lucinhu** [comment]
> Hey guys,
> 
> @coolight7 @mcLYX @lucinhu
> 
> May y'all confirm the fix:
> 
> https://github.com/alexmercerind/media_kit/actions/runs/5104934568
> 
> Do these APK crash?

It seem works fine on my emulators(Android 5.0.2 x86_64 and Android 5.1 x86_64), but no video or audio output.

> Does my APK crash?
> 
> https://github.com/alexmercerind/media_kit/actions/runs/5104934568
> 
> Scroll down for links.
> 
> I will publish an update; and then BiliYou will be updated afterwards.

On Android 6.0 x86_64 emulator: works fine!
On Android 5.0.2 and 5.1 x86_64 emulator: no video or audio output.

**Comment by alexmercerind** [comment]
Hi @lucinhu, I'm more curious about physical devices.

I also tested upon both Android 5.0 & 6.0 emulators.

The audio output has been explicitly disabled on emulators with Android 7.0 or lower. Some of these emulators have broken OpenSL ES. Same can be said for video playback; we enforce software rendering in emulators.

https://github.com/alexmercerind/media_kit/blob/ece12b3e8721ace02a4c50d5f76f0e287dd9408b/media_kit/lib/src/player/libmpv/player/real.dart#L1630-L1633

**Comment by coolight7** [comment]
> cc @coolight7

Hi,
I had test on Mi PAD 2 (Android 5.1), it is well without crash !
But there are some errors on console :
```
I/flutter ( 6991): FormatException: Invalid UTF-8 byte (at offset 58)
I/flutter ( 6991): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
I/flutter ( 6991): #1      Utf8Decoder.convert (dart:convert/utf.dart:351)
I/flutter ( 6991): #2      Utf8Codec.decode (dart:convert/utf.dart:63)
I/flutter ( 6991): #3      Utf8Pointer.toDartString (package:ffi/src/utf8.dart:49)
I/flutter ( 6991): #4      AndroidAssetLoader.loadSync (package:media_kit/src/utils/android_asset_loader.dart:57)
I/flutter ( 6991): #5      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:dio/src/compute/compute_io.dart:129)
I/flutter ( 6991): #6      Timeline.timeSync (dart:developer/timeline.dart:166)
I/flutter ( 6991): #7      _IsolateConfiguration.applyAndTime (package:media_kit/src/utils/isolates.dart:129)
I/flutter ( 6991): #8      _spawn (package:media_kit/src/utils/isolates.dart:151)
I/flutter ( 6991): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
I/flutter ( 6991): #10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
I/flutter ( 6991): {wid: 2098734, id: 0}
```

**Comment by coolight7** [comment]
On Android 11 (arm64), it sometime will output some errors on console when start app :
```
I/flutter (16815): FormatException: Unexpected extension byte (at offset 58)
I/flutter (16815): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
I/flutter (16815): #1      Utf8Decoder.convert (dart:convert/utf.dart:351)
I/flutter (16815): #2      Utf8Codec.decode (dart:convert/utf.dart:63)
I/flutter (16815): #3      Utf8Pointer.toDartString (package:ffi/src/utf8.dart:49)
I/flutter (16815): #4      AndroidAssetLoader.loadSync (package:media_kit/src/utils/android_asset_loader.dart:57)
I/flutter (16815): #5      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:dio/src/compute/compute_io.dart:129)
I/flutter (16815): #6      Timeline.timeSync (dart:developer/timeline.dart:166)
I/flutter (16815): #7      _IsolateConfiguration.applyAndTime (package:media_kit/src/utils/isolates.dart:129)
I/flutter (16815): #8      _spawn (package:media_kit/src/utils/isolates.dart:151)
I/flutter (16815): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
I/flutter (16815): #10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

**Comment by alexmercerind** [comment]
That's odd. Does video play on your Mi Pad 5?

**Comment by coolight7** [comment]
> That's odd. Does video play on your Mi Pad 2?

yea, it works well.
But it seem has a bug :
* play video. ( ok )
* play audio. ( ok )
* play video and use setProperty("audio-files", audioPath) to  set another file to be audio. ( video works well, but no audio output )

On Mi Pad 2 and my another physical device (Android 11) both no audio output if use setProperty("audio-files", audioPath) now.
On windows both video and audio work well.

Use media_kit 0.0.8 from pub.dev, both video and audio work well on Android 11 and windows.

**Comment by alexmercerind** [comment]
@coolight7, my goal is limited to offering stable & performant video & audio playback in regard to `Player` class.

And it seems it works great now.

I offer no support for internal libmpv usage (`setProperty` API is merely exposed for extreme usage or for the "sake of completion"). It's something you decide to use on your own risk. It's similar to forking the package & adding your own code. I can't guarantee support for any other internal property e.g. `audio-files` you decide to modify. You must read mpv's docs & proceed on your own. However, you must escape `:` character it seems. Learn more at https://github.com/alexmercerind/media_kit/pull/141.

**Comment by coolight7** [comment]
thanks.

**Comment by alexmercerind** [comment]
@coolight7 

<hr>

This error should not show. If this shows up, then subtitles won't work correctly.

I'm not seeing this on any of my emulators or devices. I can't reproduce it.

> On Android 11 (arm64), it sometime will output some errors on console when start app :
> 
> ```
> I/flutter (16815): FormatException: Unexpected extension byte (at offset 58)
> I/flutter (16815): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
> I/flutter (16815): #1      Utf8Decoder.convert (dart:convert/utf.dart:351)
> I/flutter (16815): #2      Utf8Codec.decode (dart:convert/utf.dart:63)
> I/flutter (16815): #3      Utf8Pointer.toDartString (package:ffi/src/utf8.dart:49)
> I/flutter (16815): #4      AndroidAssetLoader.loadSync (package:media_kit/src/utils/android_asset_loader.dart:57)
> I/flutter (16815): #5      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:dio/src/compute/compute_io.dart:129)
> I/flutter (16815): #6      Timeline.timeSync (dart:developer/timeline.dart:166)
> I/flutter (16815): #7      _IsolateConfiguration.applyAndTime (package:media_kit/src/utils/isolates.dart:129)
> I/flutter (16815): #8      _spawn (package:media_kit/src/utils/isolates.dart:151)
> I/flutter (16815): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
> I/flutter (16815): #10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
> ```

**Comment by alexmercerind** [comment]
I've published the updates:

There won't be any crashes on Android 5.0 or 6.0 etc. anymore. Thanks for report. Please don't hesitate in future.

```yaml
dependencies:
  media_kit: ^0.0.9                              # Primary package.
  
  media_kit_video: ^0.0.11                       # For video rendering.
  
  media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.0.5           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

**Comment by alexmercerind** [comment]
Hi @coolight7,

May you replace `media_kit_libs_android_video` as follows in your `pubspec.yaml` & re-build:

```yaml
dependencies:
  ...
  media_kit_libs_android_audio:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 360057d52e64251f037e67fbb47aeab2ad3d4923
      path: media_kit_libs_android_audio
```

If it works; I will update the package & roll things out. This will fix the `FormatException` bug you shared above.

A confirmation will be great. Hopefully no more issues on Android.

Thanks!

**Comment by coolight7** [comment]
> Hi @coolight7,
> 
> May you replace `media_kit_libs_android_video` as follows in your `pubspec.yaml` & re-build:
> 
> ```yaml
> dependencies:
>   ...
>   media_kit_libs_android_video:
>     git:
>       url: https://github.com/alexmercerind/media_kit.git
>       ref: 360057d52e64251f037e67fbb47aeab2ad3d4923
>       path: media_kit_libs_android_audio
> ```
> 
> If it works; I will update the package & roll things out. This will fix the `FormatException` bug you shared above.
> 
> A confirmation will be great. Hopefully no more issues on Android.
> 
> Thanks!

Hi, 
I have try it on Mi PAD 2 (Android 5.1) and Android 11, and without `FormatException`, the video and audio output work well.
But:
There are some new errors on console:
```
I/flutter ( 1770): Invalid argument(s): Failed to lookup symbol 'MediaKitAndroidHelperCopyAssetToExternalFilesDir': undefined symbol: MediaKitAndroidHelperCopyAssetToExternalFilesDir
I/flutter ( 1770): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
I/flutter ( 1770): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart)
I/flutter ( 1770): #2      AndroidAssetLoader.loadSync (package:media_kit/src/utils/android_asset_loader.dart:44)
I/flutter ( 1770): #3      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:dio/src/compute/compute_io.dart:129)
I/flutter ( 1770): #4      Timeline.timeSync (dart:developer/timeline.dart:166)
I/flutter ( 1770): #5      _IsolateConfiguration.applyAndTime (package:media_kit/src/utils/isolates.dart:129)
I/flutter ( 1770): #6      _spawn (package:media_kit/src/utils/isolates.dart:151)
I/flutter ( 1770): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
I/flutter ( 1770): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

**Comment by alexmercerind** [comment]
My apologies @coolight7,

It seems `media_kit` must also be updated in similar way, since name of symbol was changed. Something like this:

```yaml
dependencies:
  ...
  media_kit_libs_android_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 360057d52e64251f037e67fbb47aeab2ad3d4923
      path: media_kit_libs_android_audio

# Force updated media_kit with dependency_overrides.
dependency_overrides:
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: 360057d52e64251f037e67fbb47aeab2ad3d4923
      path: media_kit
 ```

**Comment by coolight7** [comment]
> My apologies @coolight7,
> 
> It seems `media_kit` must also be updated in similar way, since name of symbol was changed. 

It works well and there are no error outputs !

**Comment by alexmercerind** [comment]
Update package(s) to receive the updates:

```yaml
dependencies:
  media_kit: ^0.0.10                             # Primary package.
  
  media_kit_video: ^0.0.12                       # For video rendering.
  
  media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.0.6           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```
