### ISSUE TITLE
Buffering Stream always return false

### ISSUE THREAD

**Issue by Noobware1** [alexmercerind/media_kit#211]
i tried to render buffering stream using a stream builder to a text widget to check its state but it's always false for some reason to check if anything is wrong with my code i replaced the stream with position stream and it was updating inside the text widget but not the buffering stream.
please fix this issue.

**Comment by alexmercerind** [comment]
It works as intended. It is being used in my project.

Please file issues responsibly.

**Comment by Noobware1** [comment]
then can you show me your code that will help a lot or at least the part where you accessing the buffering value.

**Comment by clragon** [comment]
I actually also seem to be experiencing this. 
I have connected my widget to `player.streams.buffering`, but the value is _never_ true, 
even when the video is visibly buffering.

versions are:
```yml
  media_kit: ^0.0.8
  media_kit_video: ^0.0.10
  media_kit_native_event_loop: ^1.0.4
  media_kit_libs_android_video: ^1.0.4
  media_kit_libs_ios_video: ^1.0.4
  media_kit_libs_macos_video: ^1.0.5
  media_kit_libs_windows_video: ^1.0.2
  media_kit_libs_linux: ^1.0.2
```

tested on windows and android.
