### ISSUE TITLE
media_kit_video crush not letting build the app

### ISSUE THREAD

**Issue by armanhadifatah** [alexmercerind/media_kit#219]
I use latest flutter 3.10.2
I tried flutter clean also 

i get this error 
```

Launching lib/main.dart on SM S918B in debug mode...
main.dart:1
: Error: Member not found: 'VideoController.create'.
video_player_media_kit_platform_ffi.dart:80
    controllers[id] = await VideoController.create(player);
                                            ^^^^^^
: Error: The method 'dispose' isn't defined for the class 'VideoController'.
video_player_media_kit_platform_ffi.dart:264
- 'VideoController' is from 'package:media_kit_video/src/video_controller/video_controller.dart' ('../../../.pub-cache/hosted/pub.dev/media_kit_video-0.0.12/lib/src/video_controller/video_controller.dart').
video_controller.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'dispose'.
    controllers[textureId]!.dispose();
                            ^^^^^^^

Target kernel_snapshot failed: Exception
2

FAILURE: Build failed with an exception.

* Where:
Script '/Users/macbookshop/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/macbookshop/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```

This is my pubspec.yaml 
```

name: wane
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.1.9+88

environment:
  sdk: ">=2.19.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.1
  flutter_localizations:
    sdk: flutter
  intro_slider: ^4.2.0
  shared_preferences: ^2.1.1
  flutter_rating_bar: ^4.0.1
  video_player: ^2.6.1
  skeleton_text: ^3.0.0
  flutter_floating_bottom_bar: ^1.1.0
  cached_network_image: ^3.2.3
  http: ^0.13.6
  card_swiper: ^2.0.4
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_cache_manager: ^3.3.0
  country_code_picker: ^3.0.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  image_picker: ^0.8.7+5
  rounded_loading_button: ^2.1.0
  flutter_spinkit: ^5.2.0
  flutter_easyloading: ^3.0.5
  rflutter_alert: ^2.0.7
  provider: ^6.0.5
  flutter_verification_code: ^1.1.6
  rxdart: ^0.27.7
  expandable: ^5.0.1
  signal_strength_indicator: ^0.4.1
  # intl_phone_number_input: ^0.7.3+1
  intl_phone_field: ^3.1.0

  http_parser: ^4.0.2
  cloud_functions: ^4.3.2
  connectivity_plus: ^4.0.1
  webview_flutter: ^4.2.1
  permission_handler: ^10.2.0
  internet_file: ^1.2.0
  sn_progress_dialog: ^1.1.3
  #   awesome_snackbar_content: ^0.1.2
  just_audio_background: ^0.0.1-beta.9
  intl: ^0.18.0
  bluelab_dialog: ^0.0.3
  expand_widget: ^3.1.1
  logger: ^1.3.0
  timer_count_down: ^2.2.2
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.11
  flutter_udid: ^2.0.1
  flutter_svg: ^2.0.6
  flutter_downloader: ^1.10.4
  dropdown_button2: ^2.1.3
  #   open_filex: ^4.3.2

  flutter_vibrate: ^1.3.0

  #audio packages
  just_audio: ^0.9.33
  #   just_audio_background: ^0.0.1-beta.9
  audio_session: ^0.1.14

  syncfusion_flutter_sliders: ^21.2.4

  audio_service: ^0.18.9
  async: ^2.11.0
  auto_size_text: ^3.0.0
  #storage packages
  hive: ^2.2.3
  firebase_storage: ^11.2.2

  uuid: ^3.0.7
  photo_view: ^0.14.0
  firebase_messaging: ^14.6.2
  fitted_text_field_container: ^2.0.0
  timeago: ^3.4.0
  # velocity_x: ^3.6.0
  liquid_progress_indicator: ^0.4.0
  font_awesome_flutter: ^10.4.0
  avatar_glow: ^2.0.2

  flex_color_scheme: ^7.1.2
  sliding_up_panel: ^2.0.0+1
  flutter_phone_direct_caller: ^2.1.1
  animate_do: ^3.0.2
  visibility_detector: ^0.4.0+2
  in_app_review: ^2.0.6
  flutter_windowmanager: ^0.2.0

  flutter_facebook_auth: ^5.0.11
  google_api_availability: ^5.0.0
  fluttericon: ^2.0.0
  syncfusion_flutter_pdfviewer: ^21.2.4
  lottie: ^2.3.2
  flutter_credit_card: ^3.0.6
  fwfh_text_style: ^2.22.8+3
  ai_progress: ^2.0.0
  flutter_partical_button: ^0.0.1
  shimmer: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  kenburns_nullsafety: ^1.0.0
  flutter_meedu_videoplayer: ^4.2.10
  media_kit: ^0.0.9+1
  media_kit_video: ^0.0.12
  media_kit_libs_android_video: ^1.0.5
  media_kit_libs_ios_video: ^1.0.4
  media_kit_native_event_loop: ^1.0.4
  share_plus: ^6.3.4
  readmore: ^2.2.0
  firebase_dynamic_links: ^5.3.2
  wakelock: ^0.6.2
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^14.1.0
  sleek_circular_slider: ^2.0.1

#   fastpay_iraq: ^1.0.2
#   lecle_yoyo_player: ^0.0.5
#   lecle_yoyo_player: ^0.0.5+2
#   chewie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/
    - assets/logo.png
    - assets/icon_map.png
    - assets/languages/ar.json
    - assets/languages/ckb.json
    - assets/languages/en.json
    - assets/languages/kmr.json
    - assets/door.png
    - assets/phonenumber.png
    - assets/images/
    - assets/images/Card 1 (1).png
    - assets/images/Group 250.svg
    - assets/svg/
    - assets/icons/
    - assets/images/empty.svg
    - assets/images/slide1.jpg
    - assets/images/empty_list.png
    - assets/images/update_empty_state.png
    - assets/images/error_empty_state.png
    - assets/images/thinking_man.png
    - assets/images/thinking_man2.png
    - assets/icons/like_icon.png
    - assets/icons/reply_icon.png
    - assets/icons/language.png
    - assets/logo_white.png
    - assets/icons/cool_divider.png
    - assets/images/eLearning.png
    - assets/images/eLearning2.png
    - assets/loading_gif.gif
    - assets/sounds/facebook_like_sound.mp3
    - assets/facebook.svg
    - assets/images/Language.png
    - assets/rive/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: estedad
      fonts:
        - asset: assets/fonts/Estedad-Bold.ttf
        - asset: assets/fonts/Estedad-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
