### ISSUE TITLE
`player` is still `completed` even after seeking

### ISSUE THREAD

**Issue by angelocordero** [alexmercerind/media_kit#221]
When a player is `completed` and I use `player.seek()`, the player is still marked as completed, and when `player.play()` is called, the video starts playing from the beginning and not from the "seeked" position.

I know playing the video from the start when calling `player.play()` when `player.state.completed` is `true` is intended so that the player will play again from the start. But it would probably be better if the player be marked as not completed every time `player.seek()` is called so that it will start playing from the "seeked" position.

**Comment by alexmercerind** [comment]
Thanks for the report.

You have provided the recommended usage in your own comment & I will recommend the same i.e. using `play` method upon completion. Sure, I will mark `completed` as `true` if `seek` is called & add a unit test for it.

**Comment by angelocordero** [comment]
>Sure, I will mark completed as true if seek is called & add a unit test for it.

Not sure if you made a typo, but my recommendation is to mark `completed` as `false` if `seek` is called

**Comment by alexmercerind** [comment]
#223 adds the relevant fix & test.

Update package(s) to receive the updates:

```yaml
dependencies:
  media_kit: ^0.0.10                             # Primary package.
  
  media_kit_video: ^0.0.12                       # For video rendering.
  
  media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.0.6           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```
