### ISSUE TITLE
I'm getting Failed to load dynamic library 'libavcodec.so' on android

### ISSUE THREAD

**Issue by Generalomosco** [alexmercerind/media_kit#241]
I'm getting Failed to load dynamic library 'libavcodec.so' on android on Android Studio log running on windows.
```
I/flutter (27008): Invalid argument(s): Failed to load dynamic library 'libavcodec.so': dlopen failed: library "libavcodec.so" not found
I/flutter (27008): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
```

**Comment by alexmercerind** [comment]
Paste your pubspec.yaml please.

**Comment by Generalomosco** [comment]
This is my pubspac.yaml thanks!

`name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: 10.3.0
  visibility_detector: ^0.3.3
  google_fonts: 4.0.1

  go_router: 6.0.2
  camera: ^0.10.5+2

  permission_handler: ^10.2.0

  gallery_saver: 2.3.2

  image_picker: 0.8.6+1

  provider: 6.0.5
  shared_preferences: ^2.1.1

  flutter_riverpod: ^2.1.3
  media_kit: ^0.0.11
  media_kit_video: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/videos/sample.mp4
    - assets/images/placeholder.jpg
    - assets/images/banner.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
`

**Comment by alexmercerind** [comment]
As mentioned in our ["Installation"](https://github.com/alexmercerind/media_kit#for-apps-that-need-video-playback) section, you need:

```yaml
dependencies:
  media_kit: ^0.0.11                             # Primary package.
  
  media_kit_video: ^0.0.12                       # For video rendering.
  
  media_kit_native_event_loop: ^1.0.4            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.0.6           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

`media_kit_libs_*` packages provide the native libraries needed for each platform. In your case, you're missing them.

I'm not sure if our documentation is _that_ confusing.
