### ISSUE TITLE
[Enhancement] Allow media from Pipe?

### ISSUE THREAD

**Issue by TroyKomodo** [alexmercerind/media_kit#248]
I am curious about writing a player which I can provide mp4 fragments in bytes to. Similar to the [MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource) API Web Standard.
Where I write the code to handle the transport stream and just provide an mp4 file. 
In theory I could spin up a dummy webserver and serve the file over http to the player but I was curious if there was a way to do in process.

The equivalent method im looking for is
```dart
final player = Player();

final pipe = await Pipe.create();

await player.open(Media(pipe.read));

pipe.write.add(<data for the ftyp + moov>);
pipe.write.add(<data for the first n fragment>);
await pipe.write.flush();

await player.play();

// While the player is busy playing we can write more data 

pipe.write.add(<data for the first n + 1 fragment>);
await pipe.write.flush();

// We can also change the codec or submit a new file to begin playback

pipe.write.add(<data for the ftyp + moov>);
pipe.write.add(<data for the first n  + 2 fragment>);
await pipe.write.flush();
```

**Comment by alexmercerind** [comment]
Apologies! No plans for it.

Available features & codec support in [`media_kit`](https://github.com/alexmercerind/media_kit) already exceeds the official [`video_player`](https://pub.dev/packages/video_player) by a large degree.

This is as far as I'd like to go. Most Flutter applications are going to just play a video or audio file/URL of some kind; & doing that in a stable & performant way is our first goal (even more so at the moment). Secondly, we don't work at the media decoding level (in terms of abstraction). The project is primarily concerned with native interop, video rendering & etc.

We've been working on the web support internally: https://alexmercerind.github.io/media_kit, where Web API is used; so you can consume the said [MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource) API there. It's one of the major goals before the first stable 1.0.0 release; hopefully by the end of this month.

<hr>

Leaving open as "re-evaluate-in-future"; in-case scope of the project extends in future.

**Comment by TroyKomodo** [comment]
Ah I see, out of curiosity does the player support streaming of fragmented mp4 files from a webserver?

**Comment by alexmercerind** [comment]
https://github.com/media-kit/libmpv-win32-cmake/blob/04eb59e176f13b4299daa6683637fad6108ff3d4/packages/ffmpeg.cmake#L36-L64

**Comment by alexmercerind** [comment]
Hi!

Closing this one. Yes... you can actually stream through a local HTTP server; I suppose most media streaming works that way.

In fact, there is a plan to provide a caching plugin using that technique.

**Comment by alexmercerind** [comment]
Also, please update to [`package:media_kit` 1.0.0](https://github.com/alexmercerind/media_kit/releases/tag/media_kit-v1.0.0).

```yaml
dependencies:
  media_kit: ^1.0.0                              # Primary package.
  
  media_kit_video: ^1.0.0                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.5            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

Refer to the README for updated project guide.
