### ISSUE TITLE
[Enhancement][Android] content:// URI support

### ISSUE THREAD

**Issue by deckerst** [alexmercerind/media_kit#252]
Maybe I'm missing something but it seems that content URIs are not supported on Android. For example, 
```dart
player.open(Media('content://media/external/images/media/188078'));
```

Do you plan to support them?

**Comment by alexmercerind** [comment]
Thanks for pointing this out. I can think of two solutions, which [`package:media_kit`](https://github.com/alexmercerind/media_kit) may implement:

1. Reading chunks from the `content://` URI & feeding them though a local HTTP server; allowing `Player` to consume them.
2. Converting `content://` URI to it's `file://` URI by querying [`MediaStore`](https://developer.android.com/reference/android/provider/MediaStore).
  Most probably, [something like this](
https://github.com/harmonoid/harmonoid/blob/6732720e6736d1ca3f5fab331d627c0dba760a48/android/app/src/main/kotlin/com/alexmercerind/harmonoid/StorageRetriever.kt#L220-L332), subsequent calls' performance can be improved further with hashing. In general, operation should be fast, as [`MediaStore`](https://developer.android.com/reference/android/provider/MediaStore) keeps references media resources cached.

The 2 seems more "easier" & I have [a project](https://harmonoid.com) which supports Windows, GNU/Linux & Android. It internally deals with `file://` URIs primarily because it is supported on all platforms.

<hr>

Personally, I kind of don't like Android's new file-system changes; too much platform specific-ness for nothing.

**Comment by deckerst** [comment]
Solution 2) is problematic, because not all content URIs are backed by a file on storage.

I would suggest a third solution:
1) on the Android side, get a file descriptor handle from the content URI:
```kotlin
val fd = context.contentResolver.openFileDescriptor(contentUri, "r")
```
2) on the C side, open the file descriptor to read the content. Many libraries do this.

**Comment by alexmercerind** [comment]
I meant something similar in 1st solution. Reading large files may cause issue, streaming becomes a bit necessary.

**Comment by alexmercerind** [comment]
I apologize, it seems it's not as hard as I made it. You're correct.

I just read this code: 

https://github.com/bilibili/ijkplayer/blob/master/ijkmedia/ijkplayer/android/ijkplayer_jni.c#L177-L198

**Comment by alexmercerind** [comment]
How can I get some content URIs to test?

**Comment by deckerst** [comment]
If you want to fetch them yourself programmatically, you can query the Media Store on the Android side (kotlin here):
```kotlin
val projection = arrayOf(MediaStore.MediaColumns._ID)
val cursor = context.contentResolver.query(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, projection, null, null, null)
if (cursor != null) {
    val idColumn = cursor.getColumnIndexOrThrow(MediaStore.MediaColumns._ID)
    while (cursor.moveToNext()) {
        val mediaContentUri = ContentUris.withAppendedId(contentUri, cursor.getLong(idColumn))
    }
    cursor.close()
}
```

If you just want to know the content URI of a particular video, you can tweak the query above, or you could install an app like [Aves](https://github.com/deckerst/aves). In Aves, browse to the video, open its info page by a swipe up, and the content URI is there.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/pull/250 also lands content:// support for Android. Hopefully it'll be part of 1.0.0.

**Comment by alexmercerind** [comment]
You may download the latest build of our "test application" to confirm & test things etc.

**Comment by alexmercerind** [comment]
https://github.com/alexmercerind/media_kit/assets/28951144/524f7cae-51cf-4f39-9df9-ebef1d041543

**Comment by alexmercerind** [comment]
`content://` URI support is now available (with ton of other features & stability improvements) in [`package:media_kit` 1.0.0](https://github.com/alexmercerind/media_kit/releases/tag/media_kit-v1.0.0).

```yaml
dependencies:
  media_kit: ^1.0.0                              # Primary package.
  
  media_kit_video: ^1.0.0                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.5            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

Refer to the README for updated project guide.
