### ISSUE TITLE
How to get playing state as soon as possible?

### ISSUE THREAD

**Issue by joodo** [alexmercerind/media_kit#253]
``` dart
_player = Player(...);
await _player.open(...);
await _player.play();

await _player.pause();
print(_player.state.playing); // Still be "true"
await Future.delayed(
  const Duration(inMilliseconds: 100),
   () => print(_player.state.playing),
); // Should be "false" now
```

I can find 2 ways to get playing state so far:
1. 'Future.delayed' as above, but it seems unstable if the player is lagging
2. Add listener to `_player.streams.playing`, but it's not so elegant because I must do other works to make sure `print` won't triggered by other state changing

So is there any elegant way to do this?

BTW, ideally, I think `await _player.pause()` should wait until `_player.state.playing` changed to `false`.

**Comment by alexmercerind** [comment]
Please be assured that [behavior of the `Player` class is highly predictable & unit-tested. The available streams behave in a very precise manner](https://github.com/alexmercerind/media_kit/blob/sweat-and-tears/media_kit/test/src/player/player_test.dart). 

As we know, media playback is an asynchronous process involving multiple threads. For issuing normal play/pause commands, `playOrPause` method is recommended. Also, there is no way that the problem can't be solved by rewriting the code one way or another; without relying on odd behaviors. Infact, the `Player` constructor itself is asynchronous & makes all other calls like `open`, `play`, `pause` etc. wait until initialization & video-controller attachment.

I have made a commit to set `player.state.playing` explicitly in `play`/`pause` methods; hopefully all tests will still pass. A number of fixes, features & improvements will land in #250.

**Comment by alexmercerind** [comment]
Fixed once and for all in [`package:media_kit` 1.0.0](https://github.com/alexmercerind/media_kit/releases/tag/media_kit-v1.0.0).

```yaml
dependencies:
  media_kit: ^1.0.0                              # Primary package.
  
  media_kit_video: ^1.0.0                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.5            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

Refer to the README for updated project guide.
