### ISSUE TITLE
How continue playing video after reconnect the internet?

### ISSUE THREAD

**Issue by v-pavlovskyi** [alexmercerind/media_kit#254]
Two cases:
1) When opening screen without internet
2) When during playing video I disable internet and then turn on back

**Comment by alexmercerind** [comment]
Hi! We're devoting our time heavily in #250. Once that lands, you can listen to the `player.stream.error` & re-`open` that file.

**Comment by alexmercerind** [comment]
I'll update when that PR gets over the line.

**Comment by alexmercerind** [comment]
`Player.stream.error` is now available (with ton of other features & stability improvements) in [`package:media_kit` 1.0.0](https://github.com/alexmercerind/media_kit/releases/tag/media_kit-v1.0.0).

```yaml
dependencies:
  media_kit: ^1.0.0                              # Primary package.
  
  media_kit_video: ^1.0.0                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.5            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

Refer to the README for updated project guide.
