### ISSUE TITLE
[Feature Request] Clear the current Playable

### ISSUE THREAD

**Issue by MickaelHrndz** [alexmercerind/media_kit#259]
Hello,

Thank you for developing this package. Is there a reason why there isn't any kind of `clear()`/`removeAll()` method on the player ? A method that clears the player's media state would be handy. Another method could be to `reset()` the whole player as if it had just been instantiated. 

In my case, I show a placeholder below the `Video` using a `Stack`. The default `Video` + `Player` state is invisible. But once you open a media, you can't go back to an invisible state programmatically as far as I know (I'm using a `Playlist`).

**Comment by alexmercerind2** [comment]
Hi! Thanks a lot for using [`package:media_kit`](https://github.com/alexmercerind/media_kit).

I just added a new [`stop` method](https://github.com/alexmercerind/media_kit#stop) to clear the currently playing `Playable`.

<hr>

A big news is that... today I'm finally aiming for the first stable 1.0.0 release. It support for all platforms, built-in video controls & ton of other stability improvements. The updates have been added to our [README](https://github.com/alexmercerind/media_kit) along with new minimal guide to the package.

**Comment by alexmercerind** [comment]
A ton of engineering work has gone into this project.

1.0.0 means that we will no longer make breaking-changes & hold accountability for the features that have been implemented. A [large number of unit-tests](https://github.com/alexmercerind/media_kit/tree/main/media_kit/test) have been added to focus on stability & avoid regressions in future.

**Comment by alexmercerind** [comment]
`Player.stop` is now available (with ton of other features & stability improvements) in [`package:media_kit` 1.0.0](https://github.com/alexmercerind/media_kit/releases/tag/media_kit-v1.0.0).

```yaml
dependencies:
  media_kit: ^1.0.0                              # Primary package.
  
  media_kit_video: ^1.0.0                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.5            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```

Refer to the README for updated project guide.
