### ISSUE TITLE
mpv_terminate_destroy happens too late and causes unwanted pause

### ISSUE THREAD

**Issue by romaingyh** [alexmercerind/media_kit#295]
Hello thanks a lot for this amazing plugin !

I'm using the package to make an app with several video channels. I've encountered a bug when switching channel on iOS (not tested on other platform, but the bug seems to come from mpv). Here is the process:

I launch a channel => video player is created and start playing.
I leave this channel => page close, video player disposed.
I launch another channel => another player is created and start playing.
Few seconds after => the video is automatically paused.

The bug doesn't appear if you wait about 10 seconds before launching the second player.
Actually, it seems there is a delay before a player is fully destroyed, and if a disposed player is destroyed while another player is running, the latter will be paused.

Here are the logs that make me think this : 

<details>
<summary>Logs</summary>

```
# Launch the first player

Failed to change device orientation: Error Domain=UISceneErrorDomain Code=101 "None of the requested orientations are supported by the view controller. Requested: landscapeLeft, landscapeRight; Supported: portrait" UserInfo={NSLocalizedDescription=None of the requested orientations are supported by the view controller. Requested: landscapeLeft, landscapeRight; Supported: portrait}
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {id: 0, rect: {width: 0.0, top: 0.0, left: 0.0, height: 0.0}, handle: 5837419680}
flutter: NativeVideoController: Texture ID: 0
TextureGL: resize: 1280.0x720.0
flutter: VideoOutput.Resize
flutter: {rect: {width: 1280.0, height: 720.0, left: 0.0, top: 0.0}, handle: 5837419680, id: 0}



# Leave the page and dispose the first player

MediaKitEventLoopHandler::Register: std::thread exit: 5837419680
MediaKitEventLoopHandler::Dispose: 5837419680
flutter: VideoOutput.Resize
flutter: {handle: 5837419680, id: -1, rect: {width: 0.0, height: 0.0, left: 0.0, top: 0.0}}



# Launch another player

Failed to change device orientation: Error Domain=UISceneErrorDomain Code=101 "None of the requested orientations are supported by the view controller. Requested: landscapeLeft, landscapeRight; Supported: portrait" UserInfo={NSLocalizedDescription=None of the requested orientations are supported by the view controller. Requested: landscapeLeft, landscapeRight; Supported: portrait}
VideoOutput: enableHardwareAcceleration: true
flutter: VideoOutput.Resize
flutter: {handle: 5859662384, rect: {left: 0.0, top: 0.0, height: 0.0, width: 0.0}, id: 1}
flutter: NativeVideoController: Texture ID: 1
TextureGL: resize: 1920.0x1080.0
flutter: VideoOutput.Resize
flutter: {handle: 5859662384, id: 1, rect: {left: 0.0, height: 1080.0, top: 0.0, width: 1920.0}}



# Few secods after :
flutter: media_kit: mpv_terminate_destroy: 5837419680
```

</details>

<details>
<summary>My dependencies</summary>

```
  media_kit: ^1.0.2                              # Primary package.

  media_kit_video: ^1.0.2                        # For video rendering.
  
  media_kit_native_event_loop: ^1.0.6            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_video: ^1.1.1           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
````
</details>

I'm here if you need more deails or need infos to reproduce ! Thanks

**Comment by alexmercerind** [comment]
Thanks for the report.

I'm unable to understand the situation. If you call `dispose`, obviously the `Player` will be "paused".

"mpv_terminate_destroy happens too late" is a safety mechanism it's not a bug. The internal core is only disposed if no `Player` class method is called in the last 10 seconds. There was a bug in the previous update that caused memory to be not released immediately after `dispose`, but when that `mpv_terminate_destroy` gets logged. The next update will fix it, majority memory will be released immediately, about ~5 MB will be released in the perpetuity (when `mpv_terminate_destroy` happens).

<hr>

Thanks for the report. We have made a large number of optimizations either it be reducing bundle size, improving stability or further enhancing the performance. It'll be get this issue fixed before rolling next version out.

**Comment by romaingyh** [comment]
I'm sorry, English is not my primary language but I'll try to explain better.

The problem occurs when you consider two differents players. You launch a first player, we'll call it PlayerA, then you dispose this player. You then launch a tottaly different player with even a different source, PlayerB, the second player will be paused when the `mpv_terminate_destroy` event of PlayerA is called.

PlayerA is created => PlayerA disposed => PlayerB created => PlayerB paused after 10 seconds.

Idk if it's more clear but for me the second player should not be paused when `mpv_terminate_destroy` is called for the first player. Or maybe `mpv_terminate_destroy` should not be called if another player has been created in the last 10 seconds.

I'll try to make a Flutter reproductible sample and paste it here.

**Comment by alexmercerind** [comment]
Okay, I get it now.

I don't really work with macOS/iOS side; I will get back.

**Comment by birros** [comment]
I can't reproduce with [media_kit_test](https://github.com/alexmercerind/media_kit/tree/021575df2df1c209207967926da6d9e4b2e8d98d/media_kit_test) in release mode, @romaingyh can you build it yourself and try to reproduce your issue?
Using the main branch may solve your issue, @alexmercerind has made many improvements since the last stable release.
If you are able to reproduce, can you share a screencast.

**Comment by romaingyh** [comment]
Okay I can confirm the issue is not present on main branch 👍  Thanks for your help I'll wait for next release on pub.dev

Using theses dependencies :

```
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit

  media_kit_video:
    git: 
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_video
  
  media_kit_native_event_loop:
    git: 
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_native_event_loop

  media_kit_libs_ios_video:
    git: 
      url: https://github.com/alexmercerind/media_kit.git
      path: libs/ios/media_kit_libs_ios_video

  media_kit_libs_macos_video:
    git: 
      url: https://github.com/alexmercerind/media_kit.git
      path: libs/macos/media_kit_libs_macos_video
  
  ...
  
dependency_overrides: 
  win32: ^3.0.0
  http: ^1.0.0

  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit
```
