### ISSUE TITLE
[Windows] Build failed on Windows 10 and Flutter 3.7

### ISSUE THREAD

**Issue by filly82** [alexmercerind/media_kit#30]
after upgrading flutter to 3.7 following error occurs when trying to use this package
```
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Windows.
```

with `flutter run -v` shows a little bit more
```
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

Minimal example
```
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyScreen(),
    );
  }
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  final Player player = Player();
  VideoController? controller;

  @override
  void initState() {
    super.initState();
    Future.microtask(() async {
      controller = await VideoController.create(player.handle);
      setState(() {});
    });
  }

  @override
  void dispose() {
    Future.microtask(() async {
      await controller?.dispose();
      await player.dispose();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Video(
      controller: controller,
    );
  }
}
```

pubspec.yaml
```
name: media_kit_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit_video
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

```
flutter doctor -v
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale de-DE)
    • Flutter version 3.7.0 on channel stable at C:\flutter                                      
    • Upstream repository https://github.com/flutter/flutter.git                                 
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800                      
    • Engine revision b24591ed32                                                                 
    • Dart version 2.19.0                                                                        
    • DevTools version 2.20.1                                                                    
                                                                                                 
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)            

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0) 
    • Android SDK at C:\Users\Filly\AppData\Local\Android\Sdk                    
    • Platform android-33, build-tools 32.0.0                                    
    • ANDROID_HOME = C:\Users\Filly\AppData\Local\Android\Sdk                    
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.                                             
                                                                                 
[√] Chrome - develop for the web                                                 
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      
                                                                                 
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)    
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community   
    • Visual Studio Community 2022 version 17.4.33213.308                        
    • Windows 10 SDK version 10.0.22621.0                                        
                                                                                 
[√] Android Studio (version 2022.1)                                              
    • Android Studio at C:\Program Files\Android\Android Studio                  
    • Flutter plugin can be installed from:                                      
       https://plugins.jetbrains.com/plugin/9212-flutter                         
    • Dart plugin can be installed from:                                         
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\Filly\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.61

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

**Comment by filly82** [comment]
it has to do with `media_kit_video`, the above mentioned error occurs as soon as having `media_kit_video` in the dependencies list of pubspec.yaml, without even have to using it

**Comment by alexmercerind** [comment]
It's likely an access violation within C++ implementation of package:media_kit_video.

Make sure you are on latest version from Git i.e. specify the ref (latest commit hash) in your pubspec.yaml. Flutter does not detect changes in Git dependencies.

**Comment by alexmercerind** [comment]
Specify ref like this: https://github.com/alexmercerind/media_kit/issues/17#issuecomment-1383668931.

I have serious exam situation, so I'm not available before next month.

**Comment by filly82** [comment]
no hurry, but still no luck even with latest commits

it comes down to this i think

```
D:\repositories\git\entwicklung_dart\media_kit_test\windows\flutter\ephemeral\.plugin_symlinks\media_kit_video\windows\angle_surface_manager.h(15,10): fatal  error C1083: Datei (Include) kann nicht ge�ffnet werden: "EGL/egl.h": No such file or directory
[D:\repositories\git\entwicklung_dart\media_kit_test\build\windows\plugins\media_kit_video\media_kit_video_plugin.vcxproj]
[        ]   D:\repositories\git\entwicklung_dart\media_kit_test\windows\flutter\ephemeral\.plugin_symlinks\media_kit_video\windows\video_output.h(14,10): fatal  error C1083: Datei (Include) kann nicht ge�ffnet werden: "client.h": No such file or directory
[D:\repositories\git\entwicklung_dart\media_kit_test\build\windows\plugins\media_kit_video\media_kit_video_plugin.vcxproj]
[        ]   D:\repositories\git\entwicklung_dart\media_kit_test\windows\flutter\ephemeral\.plugin_symlinks\media_kit_video\windows\video_output.h(14,10): fatal  error C1083: Datei (Include) kann nicht ge�ffnet werden: "client.h": No such file or directory
[D:\repositories\git\entwicklung_dart\media_kit_test\build\windows\plugins\media_kit_video\media_kit_video_plugin.vcxproj]
[        ]   D:\repositories\git\entwicklung_dart\media_kit_test\windows\flutter\ephemeral\.plugin_symlinks\media_kit_video\windows\video_output.h(14,10): fatal  error C1083: Datei (Include) kann nicht ge�ffnet werden: "client.h": No such file or directory
[D:\repositories\git\entwicklung_dart\media_kit_test\build\windows\plugins\media_kit_video\media_kit_video_plugin.vcxproj]
[        ]   D:\repositories\git\entwicklung_dart\media_kit_test\windows\flutter\ephemeral\.plugin_symlinks\media_kit_video\windows\video_output.h(14,10): fatal  error C1083: Datei (Include) kann nicht ge�ffnet werden: "client.h": No such file or directory
[D:\repositories\git\entwicklung_dart\media_kit_test\build\windows\plugins\media_kit_video\media_kit_video_plugin.vcxproj]

```

i think i got that right with the ref

```
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit
      ref: c63aecfbe4db223b11a27a12ad261832fe8d0c36
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit_video
      ref: 13ab81338b3ba88fd0be7196edfd18805741dd93
```

**Comment by alexmercerind** [comment]
20c46b58bb5c8a9e749b6b9760234281e7bf2e02 is latest ref. 
Use it for both packages. Confirm if it still crashes. If not, close this.

**Comment by filly82** [comment]
unfortunately it still crashes

```
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit
      ref: 20c46b58bb5c8a9e749b6b9760234281e7bf2e02
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit
      path: media_kit_video
      ref: 20c46b58bb5c8a9e749b6b9760234281e7bf2e02
```
