### ISSUE TITLE
[Question] New release soon? No media_kit_libs_macos_video package on pub.dev

### ISSUE THREAD

**Issue by driss-bonbot** [alexmercerind/media_kit#77]
Have been testing this and it's really cool! Works like a charm on linux!
As the title suggests: Any ETA on next release? The macos package isn't available on pub.dev

Thanks!

**Comment by jiangchunyu** [comment]
i have the same problem

Because media_kit_all_test depends on media_kit_libs_macos_video any which doesn't exist (could not find package media_kit_libs_macos_video at https://pub.flutter-io.cn), version solving failed

**Comment by birros** [comment]
You don't have to wait for a new release to use the current version, just change the dependencies in your `pubspec.yaml`:

```yaml
dependencies:
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: ./media_kit_libs_macos_video
  media_kit_native_event_loop:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: ./media_kit_native_event_loop
```
