### ISSUE TITLE
when is the new release due?

### ISSUE THREAD

**Issue by dkliss** [alexmercerind/media_kit#875]
Hi, 

It seems the last release of this package was 8 months ago? Is there a planned date for new release as it seems there has been few fixed in past 8 months?

Thanks!

**Comment by abdelaziz-mahdy** [comment]
https://github.com/media-kit/media-kit/pull/845 but you can use github version 

```
dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```
