### ISSUE TITLE
Entering and exiting fullscreen pauses video on web

### ISSUE THREAD

**Issue by meowofficial** [alexmercerind/media_kit#935]
Entering and exiting fullscreen pauses playing video on web. It happens most of the time, but not always.

Code sample from the plugin page:

```dart
// Make sure to add following packages to pubspec.yaml:
// * media_kit
// * media_kit_video
// * media_kit_libs_video
import 'package:flutter/material.dart';

import 'package:media_kit/media_kit.dart';                      // Provides [Player], [Media], [Playlist] etc.
import 'package:media_kit_video/media_kit_video.dart';          // Provides [VideoController] & [Video] etc.

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // Necessary initialization for package:media_kit.
  MediaKit.ensureInitialized();
  runApp(
    const MaterialApp(
      home: MyScreen(),
    ),
  );
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key}) : super(key: key);
  @override
  State<MyScreen> createState() => MyScreenState();
}

class MyScreenState extends State<MyScreen> {
  // Create a [Player] to control playback.
  late final player = Player();
  // Create a [VideoController] to handle video output from [Player].
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    // Play a [Media] or [Playlist].
    player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.width * 9.0 / 16.0,
        // Use [Video] widget to display video output.
        child: Video(controller: controller),
      ),
    );
  }
}
```

media_kit: ^1.1.11
media_kit_video: ^1.2.5
media_kit_libs_video: ^1.0.5

**Comment by Prince-of-death** [comment]
experiencing same thing

**Comment by mbfakourii** [comment]
@alexmercerind

You might check this out

**Comment by Prince-of-death** [comment]
on completely unrelated topic using `late final controller = VideoController(player);` initializing video controller outside the initstate causes some issues on some platforms

> Entering and exiting fullscreen pauses playing video on web. It happens most of the time, but not always.
> 
> Code sample from the plugin page:
> 
> ```dart
> // Make sure to add following packages to pubspec.yaml:
> // * media_kit
> // * media_kit_video
> // * media_kit_libs_video
> import 'package:flutter/material.dart';
> 
> import 'package:media_kit/media_kit.dart';                      // Provides [Player], [Media], [Playlist] etc.
> import 'package:media_kit_video/media_kit_video.dart';          // Provides [VideoController] & [Video] etc.
> 
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
>   // Necessary initialization for package:media_kit.
>   MediaKit.ensureInitialized();
>   runApp(
>     const MaterialApp(
>       home: MyScreen(),
>     ),
>   );
> }
> 
> class MyScreen extends StatefulWidget {
>   const MyScreen({Key? key}) : super(key: key);
>   @override
>   State<MyScreen> createState() => MyScreenState();
> }
> 
> class MyScreenState extends State<MyScreen> {
>   // Create a [Player] to control playback.
>   late final player = Player();
>   // Create a [VideoController] to handle video output from [Player].
>   late final controller = VideoController(player);
> 
>   @override
>   void initState() {
>     super.initState();
>     // Play a [Media] or [Playlist].
>     player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
>   }
> 
>   @override
>   void dispose() {
>     player.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Center(
>       child: SizedBox(
>         width: MediaQuery.of(context).size.width,
>         height: MediaQuery.of(context).size.width * 9.0 / 16.0,
>         // Use [Video] widget to display video output.
>         child: Video(controller: controller),
>       ),
>     );
>   }
> }
> ```
> 
> media_kit: ^1.1.11 media_kit_video: ^1.2.5 media_kit_libs_video: ^1.0.5

**Comment by alexmercerind** [comment]
Use main branch.

**Comment by mbfakourii** [comment]
> Use main branch.

For which package should you use main to solve the problem because we have three packages

**Comment by alexmercerind** [comment]
All...

**Comment by mbfakourii** [comment]
Temporary solution for this problem

```dart
Video(
  ...
  onEnterFullscreen: () {
    if (kIsWeb && widget.controller.player.state.playing) {
      Timer(const Duration(milliseconds: 100), () {
        widget.controller.player.play();
      });
    }

    return defaultEnterNativeFullscreen();
  },
  onExitFullscreen: () {
    if (kIsWeb && widget.controller.player.state.playing) {
      Timer(const Duration(milliseconds: 100), () {
        widget.controller.player.play();
      });
    }

    return defaultExitNativeFullscreen();
  },
  ...
),
```

**Comment by Prince-of-death** [comment]
@alexmercerind when will the current main branch will be released. Most the packages like screen_brightness are outdated

**Comment by bsogulcan** [comment]
Hi, I’m using the main branch. The player pauses when entering fullscreen, but this issue occurs only on iOS. It works correctly on Android, Windows, and macOS—no pausing happens there.

By the way my `pubspec.yaml` looks like this:

```
dependencies:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit
      ref: main

  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
      ref: main

  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: libs/universal/media_kit_libs_video
      ref: main

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit
      ref: main

  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
      ref: main

  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: libs/universal/media_kit_libs_video
      ref: main

```
